image: nixos/unstable
packages:
  - nixos.python38Packages.poetry
sources:
  - https://git.sr.ht/~sumner/tracktime
secrets:
  # PyPi Deploy Credentials for Tracktime
  - d5c21a37-01c0-403c-a9d4-ff7f31095b92
environment:
  PROJECT_NAME: tracktime
triggers:
  - action: email
    condition: failure
    to: ~sumner/tracktime-devel@lists.sr.ht
tasks:
  - setup: |
      cd ${PROJECT_NAME}
      poetry install
      echo "cd ${PROJECT_NAME}" >> ~/.buildenv
      echo "source $(poetry env info -p)/bin/activate" >> ~/.buildenv

  - lint: |
      poetry check
      flake8
      mypy ${PROJECT_NAME}
      black --check .
      .builds/bin/custom_style_check.py

  # TODO figure out how to publish htmlcov files
  - test: |
      pytest

  - build: |
      poetry build

  - deploy: |
      poetry publish --dry-run
      .builds/bin/run_if_tagged_with_version "poetry publish"
